apiVersion: v1
kind: Service
metadata:
  name: client-node-port

spec:
  # NodePort is the only type that allows us to specify a port and expose the container to the world
  # used in development, not used for production (only in some exceptions) 
  type: NodePort
  ports:
  - port: 3050
    targetPort: 3000
    nodePort: 31515
  selector:
    # This is the same as the label in client-pod.yaml
    app: client-pod
    component: web